introduction/urls.py
from django.urls import path
from . import views

app_name='introduction'
urlpatterns = [
    path('', views.profile, name="profile"),
]

myblog/urls.py
from django.contrib import admin
from django.urls import path, include
from . import views
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('introduction/', include('introduction.urls')),
    path('', views.main, name="main"),
    path('posts/', include('posts.urls')),
    path('accounts/', include('allauth.urls')),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

posts/urls.py
from django.urls import path
from .views import *

app_name="posts"
urlpatterns = [
    path('new/', new, name="new"),
    path('create/', create, name="create"),
    path('', main, name="main"),
    path('<int:post_id>/', show, name="show"),
    path('<int:post_id>/edit/', update, name="update"),
    path('<int:post_id>/delete/', delete, name="delete"),
    path('<int:post_id>/create_comment', create_comment, name="create_comment"),
]

introduction/models.py
from django.db import models

# Create your models here.

posts/models.py
from django.db import models
from django.contrib.auth.models import User

# Create your models here.
class Post(models.Model):
    title = models.CharField(max_length=50, null=False)
    content = models.TextField()
    writer = models.ForeignKey(User, on_delete=models.CASCADE, null=True)
    view_count = models.IntegerField(default=0)
    image = models.ImageField(upload_to='images/', null=True)
    created_at = models.DateTimeField(auto_now_add = True)
    updated_at = models.DateTimeField(auto_now = True)


class Comment(models.Model):
    content = models.TextField()
    writer = models.ForeignKey(User, on_delete=models.CASCADE)
    post = models.ForeignKey(Post, on_delete=models.CASCADE, related_name='comments')
    created_at = models.DateTimeField(auto_now_add = True)
    updated_at = models.DateTimeField(auto_now = True)
    

introduction/views.py
from django.shortcuts import render

# Create your views here.
def profile(request):
    return render(request, 'introduction/profile.html')

myblog/views.py
from django.shortcuts import render

def main(request):
    return render(request, 'main.html')

posts/views.py
from django.shortcuts import render, redirect, get_object_or_404
from .models import Post, Comment

# Create your views here.
def new(request):
    return render(request, 'posts/new.html')


def create(request):
    if request.method == "POST":
        title = request.POST.get('title')
        content = request.POST.get('content')
        writer = request.user
        image = request.FILES.get('image')
        Post.objects.create(title=title, content=content, writer=writer, image=image)
    return redirect('posts:main')


def main(request):
    posts = Post.objects.all().order_by('-created_at')
    return render(request, 'posts/main.html', {'posts': posts})


def show(request, post_id):
    post = Post.objects.get(pk=post_id)
    post.view_count += 1
    post.save()
    all_comments = post.comments.all().order_by('-created_at')
    return render(request, 'posts/show.html', {'post': post, 'comments': all_comments })


def update(request, post_id):
    post = get_object_or_404(Post, pk=post_id)
    if request.method == "POST":
        post.title = request.POST['title']
        post.content = request.POST['content']
        post.image = request.FILES.get('image')
        post.save()
        return redirect('posts:show', post.id)
    return render(request, 'posts/edit.html', {"post": post})


def delete(request, post_id):
    post = get_object_or_404(Post, pk=post_id)
    post.delete()
    return redirect('posts:main')


def create_comment(request, post_id):
    if request.method == "POST":
        post = get_object_or_404(Post, pk=post_id)
        current_user = request.user
        comment_content = request.POST.get('content')
        Comment.objects.create(content=comment_content, writer=current_user, post=post)
    return redirect('posts:show', post_id)

introduction/templates/introduction/profile.html
{% extends 'base.html' %}

{% block content %}
{% include 'shared/_navbar.html' %}
<h1>자기소개 페이지</h1>
{% endblock %}

myblog/templates/base.html
{% load static %}

<!doctype html>
<html lang="en">
  <head>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

    <!-- Bootstrap CSS -->
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.5.0/css/bootstrap.min.css" integrity="sha384-9aIt2nRpC12Uk9gS9baDl411NQApFmC26EwAOH8WgZl5MYYxFfc+NcPb1dKGj7Sk" crossorigin="anonymous">
    <link rel="stylesheet" href="{% static 'css/project.css' %}">
    <title>My Blog</title>
  </head>
  <body>

    {% block content %}
    {% endblock %}

    <!-- Optional JavaScript -->
    <!-- jQuery first, then Popper.js, then Bootstrap JS -->
    <script src="https://code.jquery.com/jquery-3.5.1.slim.min.js" integrity="sha384-DfXdz2htPH0lsSSs5nCTpuj/zy4C+OGpamoFVy38MVBnE+IbbVYUew+OrCXaRkfj" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.0/dist/umd/popper.min.js" integrity="sha384-Q6E9RHvbIyZFJoft+2mJbHaEWldlvI9IOYy5n3zV9zzTtmI3UksdQRVvoxMfooAo" crossorigin="anonymous"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.5.0/js/bootstrap.min.js" integrity="sha384-OgVRvuATP1z7JjHLkuOU7Xw704+h835Lr+6QL9UvYjZE3Ipu6Tp75j7Bh/kR0JKI" crossorigin="anonymous"></script>
  </body>
</html>

myblog/templates/main.html
{% extends 'base.html' %}
{% load static %}

{% block content %}
{% include 'shared/_navbar.html' %}
<h1>메인 페이지</h1>
<img src="{% static 'images/profile.jpg' %}">
{% endblock %}

myblog/templates/shared/_navbar.html
<nav class="navbar navbar-expand-lg navbar-light bg-light">
    <a class="navbar-brand" href="{% url 'main' %}">My Blog</a>
  
    <div class="collapse navbar-collapse" id="navbarSupportedContent">
      <ul class="navbar-nav mr-auto">
        <li class="nav-item active">
          <a class="nav-link" href="{% url 'main' %}">Home <span class="sr-only">(current)</span></a>
        </li>
        <li class="nav-item">
          <a class="nav-link" href="{% url 'introduction:profile' %}">Profile</a>
        </li>
        <li class="nav-item">
          <a class="nav-link" href="{% url 'posts:main' %}">Post</a>
        </li>
        <li class="nav-item">
          <a class="nav-link" href="{% url 'posts:new' %}">New</a>
        </li>
        {% if user.is_authenticated %}
        <li class="nav-item">
          <a class="nav-link" href="{% url 'account_logout' %}">로그아웃</a>
        </li>
        <li class="nav-item">
          <a class="nav-link" href="{% url 'account_change_password' %}">비밀번호 변경</a>
        </li>
        {% else %}
        <li class="nav-item">
          <a class="nav-link" href="{% url 'account_login' %}">로그인</a>
        </li>
        <li class="nav-item">
          <a class="nav-link" href="{% url 'account_signup' %}">회원가입</a>
        </li>
        {% endif %}
        </ul>
    </div>
</nav>

posts/templates/posts/edit.html
{% extends 'base.html' %}

{% block content %}
<div class="container">
    <h1>글 수정하기</h1> <!-- edit 페이지니까 글 수정하기로 변경 -->
    <form action="{% url 'posts:update' post.pk %}" method="POST" enctype="multipart/form-data"> <!-- update 기능이니까 url 이름도 update로 해줍시다. -->
        {% csrf_token %}
        <div class="form-group">
            <label for="title">글 제목</label>
            <input type="text" class="form-control" name="title" id="title" placeholder="제목을 입력해주세요." value="{{ post.title }}" required> <!-- value 속성 추가 -->
        </div>
        <div class="form-group">
            <label for="content">글 내용</label>
            <textarea class="form-control" name="content" id="content" placeholder="내용을 입력해 주세요...">{{ post.content }}</textarea> <!-- 글 내용 추가 -->
        </div>
        <div class="form-group">
            <label>이미지 첨부</label>
            <input type="file", class="form-control" name="image" accept="image/*">
        </div>
        <input type="submit" value="글 수정" class="btn btn-outline-primary"> <!-- 수정으로 버튼 변경 -->
    </form>
</div>
{% endblock %}

posts/templates/posts/main.html
{% extends 'base.html' %}
{% load static %}

{% block content %}
{% include 'shared/_navbar.html' %}
<div class="container">
    {% if user.is_authenticated %}
        <h1>글 목록</h1>
        <div class="row">
            {% for post in posts %}
                <div class="col-md-4 col-12">
                    <div class="card" style="width: 18rem; margin-top: 20px;">
                        <div class="card-body">
                            <h5 class="card-title">{{ post.title }}</h5>
                            <p>조회수 : {{ post.view_count }}</p>
                            <a href="{% url 'posts:show' post.id %}" class="btn btn-primary">상세보기</a>
                        </div>
                    </div>
                </div>
            {% endfor %}
        </div>
    {% else %}
        <h3>로그인 후 이용이 가능합니다.</h3>
        <a href="{% url 'account_login' %}" class="btn btn-warning">로그인</a>
        <a href="{% url 'account_signup' %}" class="btn btn-warning">회원가입</a>
    {% endif %}
</div>
{% endblock %}

posts/templates/posts/new.html
{% extends 'base.html' %}

{% block content %}
<div class="container">
    <h1>새로운 글 작성하기</h1>
    <form action="{% url 'posts:create' %}" method="POST" enctype="multipart/form-data">
        {% csrf_token %}
        <div class="form-group">
            <label for="title">글 제목</label>
            <input type="text" class="form-control" name="title" id="title" placeholder="제목을 입력해주세요." required>
        </div>
        <div class="form-group">
            <label for="content">글 내용</label>
            <textarea class="form-control" name="content" id="content" placeholder="내용을 입력해 주세요..."></textarea>
        </div>
        <div class="form-group">
            <label>이미지 첨부</label>
            <input type="file", class="form-control" name="image" accept="image/*">
        </div>
        <input type="submit" value="글 작성" class="btn btn-outline-primary">
    </form>
</div>
{% endblock %}

posts/templates/posts/show.html
{% extends 'base.html' %}

{% block content %}
{% include 'shared/_navbar.html' %}
<div class="container">
    <h1>글 #{{ post.id }} 상세보기</h1>
    <h3>글 제목 : {{ post.title }}</h3>
    {% if post.writer %}
        {% if post.writer.username == 'user' %}
        <h3>작성자 : {{ post.writer.last_name }} {{ post.writer.first_name }}</h3>
        {% else %}
        <h3>작성자 : {{ post.writer }}</h3>
        {% endif %}
    {% else %}
        <h3>작성자 : 알 수 없음</h3>
    {% endif %}
    <h3>조회수 : {{ post.view_count }}</h3>
    <h3>글 내용 : {{ post.content }}</h3>
    <h3>작성 시각 : {{ post.created_at }}</h3>
    <h3>수정 시각 : {{ post.updated_at }}</h3>
    {% if post.image %}
        <img src="{{ post.image.url }}" alt="사진">
    {% endif %}

    {% if user == post.writer %}
        <a href="{% url 'posts:update' post.pk %}" class="btn btn-primary">수정</a>
        <a href="{% url 'posts:delete' post.pk %}" class="btn btn-danger">삭제</a>
    {% endif %}
</div>
<div class="container mt-5">
    <form class="form-row" action="{% url 'posts:create_comment' post.id %}" method="POST">
        {% csrf_token %}
        <textarea class="form-control col-11 mr-2" name="content" placeholder="댓글 내용 입력..."></textarea>
        <input type="submit" class="btn btn-primary" value="확인">
    </form>
</div>
<div class="container mt-5 mb-5">
    {% for comment in comments %}
    <div class="card">
        <div class="card-body">
            <b>{{ comment.writer }}</b> : {{ comment.content }}<br>
            <small>{{ comment.created_at }}</small>
        </div>
    </div>
    {% endfor %}
</div>
{% endblock %}